<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-10T19:43:22 IST" name="Suite" finished-at="2024-12-10T19:43:51 IST" duration-ms="29234">
    <groups>
      <group name="error">
        <method signature="Errorvalidation.invalidFormat()[pri:0, instance:testgroup.testpackage.Errorvalidation@67d48005]" name="invalidFormat" class="testgroup.testpackage.Errorvalidation"/>
        <method signature="Errorvalidation.wrongCreds()[pri:0, instance:testgroup.testpackage.Errorvalidation@67d48005]" name="wrongCreds" class="testgroup.testpackage.Errorvalidation"/>
      </group> <!-- error -->
    </groups>
    <test started-at="2024-12-10T19:43:22 IST" name="Test" finished-at="2024-12-10T19:43:51 IST" duration-ms="29234">
      <class name="testgroup.testpackage.Errorvalidation">
        <test-method is-config="true" signature="startapp()[pri:0, instance:testgroup.testpackage.Errorvalidation@67d48005]" started-at="2024-12-10T19:43:22 IST" name="startapp" finished-at="2024-12-10T19:43:40 IST" duration-ms="17995" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startapp -->
        <test-method signature="invalidFormat()[pri:0, instance:testgroup.testpackage.Errorvalidation@67d48005]" started-at="2024-12-10T19:43:40 IST" name="invalidFormat" finished-at="2024-12-10T19:43:41 IST" duration-ms="1012" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [*Enter Valid Email] but found [*Enter Valid Emai]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [*Enter Valid Email] but found [*Enter Valid Emai]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testgroup.testpackage.Errorvalidation.invalidFormat(Errorvalidation.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidFormat -->
        <test-method is-config="true" signature="endTest()[pri:0, instance:testgroup.testpackage.Errorvalidation@67d48005]" started-at="2024-12-10T19:43:41 IST" name="endTest" finished-at="2024-12-10T19:43:42 IST" duration-ms="520" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method is-config="true" signature="startapp()[pri:0, instance:testgroup.testpackage.Errorvalidation@67d48005]" started-at="2024-12-10T19:43:42 IST" name="startapp" finished-at="2024-12-10T19:43:49 IST" duration-ms="7221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startapp -->
        <test-method signature="wrongCreds()[pri:0, instance:testgroup.testpackage.Errorvalidation@67d48005]" started-at="2024-12-10T19:43:49 IST" name="wrongCreds" finished-at="2024-12-10T19:43:51 IST" duration-ms="1909" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongCreds -->
        <test-method is-config="true" signature="endTest()[pri:0, instance:testgroup.testpackage.Errorvalidation@67d48005]" started-at="2024-12-10T19:43:51 IST" name="endTest" finished-at="2024-12-10T19:43:51 IST" duration-ms="465" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- testgroup.testpackage.Errorvalidation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
